build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - cinst mingw
  - set PATH=C:\MinGW\bin;C:\tools\mingw64\bin;%PATH%
  - python build.py
